### ISSUE TITLE
java.lang.NoSuchMethodError: org.apache.hadoop.hive.ql.security.authorization.plugin.HiveAuthzContext.getForwardedAddresses()Ljava/util/List;

### ISSUE THREAD

**Issue by mvignesh1990** [yaooqinn/spark-authorizer#15]
### Normally running show databases from spark shell works. But after importing and adding to experimental optimizations, it gives the error as follows. Using Spark 2.2.0/Hive 2.2.0:

java.lang.NoSuchMethodError: org.apache.hadoop.hive.ql.security.authorization.plugin.HiveAuthzContext.getForwardedAddresses()Ljava/util/List;
  at org.apache.ranger.authorization.hive.authorizer.RangerHiveAccessRequest.<init>(RangerHiveAccessRequest.java:56)
  at org.apache.ranger.authorization.hive.authorizer.RangerHiveAuthorizer.checkPrivileges(RangerHiveAuthorizer.java:296)
  at org.apache.spark.sql.hive.DefaultAuthorizerImpl$$anonfun$checkPrivileges$1.apply(DefaultAuthorizerImpl.scala:107)
  at org.apache.spark.sql.hive.DefaultAuthorizerImpl$$anonfun$checkPrivileges$1.apply(DefaultAuthorizerImpl.scala:102)
  at scala.Option.foreach(Option.scala:257)
  at org.apache.spark.sql.hive.DefaultAuthorizerImpl.checkPrivileges(DefaultAuthorizerImpl.scala:102)
  at org.apache.spark.sql.catalyst.optimizer.Authorizer$.apply(Authorizer.scala:66)
  at org.apache.spark.sql.catalyst.optimizer.Authorizer$.apply(Authorizer.scala:42)
  at org.apache.spark.sql.catalyst.rules.RuleExecutor$$anonfun$execute$1$$anonfun$apply$1.apply(RuleExecutor.scala:85)
  at org.apache.spark.sql.catalyst.rules.RuleExecutor$$anonfun$execute$1$$anonfun$apply$1.apply(RuleExecutor.scala:82)
  at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
  at scala.collection.immutable.List.foldLeft(List.scala:84)
  at org.apache.spark.sql.catalyst.rules.RuleExecutor$$anonfun$execute$1.apply(RuleExecutor.scala:82)
  at org.apache.spark.sql.catalyst.rules.RuleExecutor$$anonfun$execute$1.apply(RuleExecutor.scala:74)
  at scala.collection.immutable.List.foreach(List.scala:381)
  at org.apache.spark.sql.catalyst.rules.RuleExecutor.execute(RuleExecutor.scala:74)
  at org.apache.spark.sql.execution.QueryExecution.optimizedPlan$lzycompute(QueryExecution.scala:78)
  at org.apache.spark.sql.execution.QueryExecution.optimizedPlan(QueryExecution.scala:78)
  at org.apache.spark.sql.execution.QueryExecution.sparkPlan$lzycompute(QueryExecution.scala:84)
  at org.apache.spark.sql.execution.QueryExecution.sparkPlan(QueryExecution.scala:80)
  at org.apache.spark.sql.execution.QueryExecution.executedPlan$lzycompute(QueryExecution.scala:89)
  at org.apache.spark.sql.execution.QueryExecution.executedPlan(QueryExecution.scala:89)
  at org.apache.spark.sql.Dataset.<init>(Dataset.scala:182)
  at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:67)
  at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:623)
  ... 48 elided

**Comment by yaooqinn** [comment]
I guess that you use hive ranger plugin higher than 0.5.3; `HiveAuthzContext.getForwardedAddresses` does not exist in `HiveAuthzContext.class` packed in the spark's hive client jar(hive-xxx-1.2.1.spark2.jar)

**Comment by mvignesh1990** [comment]
You're Right. Worked for 0.5.3 plugins. But the authorizations only happen for use/show database commands from spark-shell only. Doesn't work for other queries. Able to access table via dbname.tablename for unauthorized db. And it doesn't work from beeline. Any pointers on what I might be missing?

Edit: I am using the master branch build, using spark-2.2 profile on ranger-0.5.3 plugins.

**Comment by yaooqinn** [comment]
It should works for any queries. I suggest you turn on debug mode to see what is going on actually. 

If you were trying beeline for multi tenancy, you may try https://github.com/yaooqinn/kyuubi

**Comment by mvignesh1990** [comment]
It seems to work in a certain cluster. But when i try replicating the same in another cluster, i am facing this issue. Only DB level statements go through the authorizer. All others are not.

I also keep getting: RangerHiveAuthorizerBase.RangerHiveAuthorizerBase(): hiveAuthenticator.getUserName() returned null/empty
is that OK? This shows up in the cluster where it works as well.

Edit:
I did some debugging, and found that for the method
AuthzImpl.checkPrivileges, the input object goes as null/empty.

### Working Cluster:
    In Check Privileges : 
    sparkSession : org.apache.spark.sql.SparkSession@a23b96b 
    HiveOperationType :  QUERY
    InpObj : [Object [type=TABLE_OR_VIEW, name=default.test_data[]]]
    OutObj : []
    Context: HiveAuthzContext [userIpAddress=null, commandString=null]

### Non-Working Cluster:
    In Check Privileges : 
    sparkSession : org.apache.spark.sql.SparkSession@6edc8385 
    HiveOperationType :  QUERY
    InpObj : []
    OutObj : []
    Context: HiveAuthzContext [userIpAddress=null, commandString=null]

It seems none of the cases match for PrivilegesBuilder.buildQuery. The object being matched is of type CatalogRelation, that doesn't match the cases.

**Comment by mvignesh1990** [comment]
Fixed it by adding CatalogRelation to the switch/case in buildQuery. Works for spark-shell but doesn't work for beeline.

The call to authz.checkPriveleges should ideally throw an HiveAccess exception and fail causing auth error. But from beeline, it doesn't throw the exception.

**Comment by yaooqinn** [comment]
what was  your beeline cconnected with？
how about share your configurations？

**Comment by yaooqinn** [comment]
I could not found a class named CatalogRelation in spark source code, did I get the wrong version of spark?

**Comment by mvignesh1990** [comment]
> I could not found a class named CatalogRelation in spark source code, did I get the wrong version of spark?

Hi @yaooqinn ,
I am using the following setup:
Spark : Spark Version 2.2.0 scala-2.11.8
Hive : Hive 2.2.0
Ranger Admin: 0.7.1
Ranger Plugin in spark/jars: 0.5.3
Spark-Authorizer: branch = master, build command: mvn package -Pspark-2.2

Attaching the configs.



[configs.zip](https://github.com/yaooqinn/spark-authorizer/files/2839563/configs.zip)

**Comment by mvignesh1990** [comment]
> what was your beeline cconnected with？
> how about share your configurations？

Was able to fix this issue. The doAs property was set to false. Changing it to true worked. But the CatalogRelation change is still required.

**Comment by mvignesh1990** [comment]
Hi @yaooqinn ,
I found the change for CatalogRelation was required in my cluster. This might be an issue in some other clusters too. Can I give a Pull Request and contribute my changes on top of it?

**Comment by yaooqinn** [comment]
feel free to submit your pr.

**Comment by mvignesh1990** [comment]
Thanks @yaooqinn . PFB my PR for the same. Let me know in case of any changes required.
https://github.com/yaooqinn/spark-authorizer/pull/16
