### ISSUE TITLE
虽然hive授权可以使用，但是如果hadoop开启了kerberos认证，到hadoop那一步会被拦截，这个有考虑过么，大神

### ISSUE THREAD

**Issue by xhmz** [yaooqinn/spark-authorizer#23]
Caused by: org.apache.hadoop.ipc.RemoteException(org.apache.hadoop.security.AccessControlException): Permission denied: user=user1, access=EXECUTE, inode="/user/hive/warehouse/aa1.db/t1":user2:supergroup:drwxr-----
	at org.apache.hadoop.hdfs.server.namenode.FSPermissionChecker.check(FSPermissionChecker.java:319)
	at org.apache.hadoop.hdfs.server.namenode.FSPermissionChecker.checkTraverse(FSPermissionChecker.java:259)
	at org.apache.hadoop.hdfs.server.namenode.FSPermissionChecker.checkPermission(FSPermissionChecker.java:205)

**Comment by yaooqinn** [comment]
你这边元数据和数据的权限不同步，这块应该在ranger中做元数据权变更的同时，增加hdfs的acl权限

**Comment by xhmz** [comment]
这个是一个解决方案，
