### ISSUE TITLE
Permission denied: user information not available

### ISSUE THREAD

**Issue by spacenorden** [yaooqinn/spark-authorizer#4]
Hi Kent,

I'm trying to get spark-authorizer to work, but apparently I'm missing something. I can't get past this error:

```
scala> spark.sql("show databases").show
2018-09-22 10:12:28 WARN  RangerHiveAuthorizerBase:70 - RangerHiveAuthorizerBase.RangerHiveAuthorizerBase(): hiveAuthenticator.getUserName() returned null/empty
2018-09-22 10:12:29 ERROR AuthzImpl$:56 -
+===============================+
|Spark SQL Authorization Failure|
|-------------------------------|
|Permission denied: user information not available
|-------------------------------|
|Spark SQL Authorization Failure|
+===============================+

org.apache.hadoop.hive.ql.security.authorization.plugin.HiveAccessControlException: Permission denied: user information not available
  at org.apache.ranger.authorization.hive.authorizer.RangerHiveAuthorizer.checkPrivileges(RangerHiveAuthorizer.java:207)
  at org.apache.spark.sql.hive.client.AuthzImpl$.checkPrivileges(AuthzImpl.scala:73)
  at org.apache.spark.sql.catalyst.optimizer.Authorizer$$anonfun$apply$1.apply(Authorizer.scala:66)
  at org.apache.spark.sql.catalyst.optimizer.Authorizer$$anonfun$apply$1.apply(Authorizer.scala:62)
  at scala.Option.foreach(Option.scala:257)
  at org.apache.spark.sql.catalyst.optimizer.Authorizer$.apply(Authorizer.scala:62)
  at org.apache.spark.sql.catalyst.optimizer.Authorizer$.apply(Authorizer.scala:47)
  at org.apache.spark.sql.catalyst.rules.RuleExecutor$$anonfun$execute$1$$anonfun$apply$1.apply(RuleExecutor.scala:87)
  at org.apache.spark.sql.catalyst.rules.RuleExecutor$$anonfun$execute$1$$anonfun$apply$1.apply(RuleExecutor.scala:84)
  at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
  at scala.collection.immutable.List.foldLeft(List.scala:84)
  at org.apache.spark.sql.catalyst.rules.RuleExecutor$$anonfun$execute$1.apply(RuleExecutor.scala:84)
  at org.apache.spark.sql.catalyst.rules.RuleExecutor$$anonfun$execute$1.apply(RuleExecutor.scala:76)
  at scala.collection.immutable.List.foreach(List.scala:381)
  at org.apache.spark.sql.catalyst.rules.RuleExecutor.execute(RuleExecutor.scala:76)
  at org.apache.spark.sql.execution.QueryExecution.optimizedPlan$lzycompute(QueryExecution.scala:66)
  at org.apache.spark.sql.execution.QueryExecution.optimizedPlan(QueryExecution.scala:66)
  at org.apache.spark.sql.execution.QueryExecution.sparkPlan$lzycompute(QueryExecution.scala:72)
  at org.apache.spark.sql.execution.QueryExecution.sparkPlan(QueryExecution.scala:68)
  at org.apache.spark.sql.execution.QueryExecution.executedPlan$lzycompute(QueryExecution.scala:77)
  at org.apache.spark.sql.execution.QueryExecution.executedPlan(QueryExecution.scala:77)
  at org.apache.spark.sql.Dataset.withAction(Dataset.scala:3249)
  at org.apache.spark.sql.Dataset.<init>(Dataset.scala:190)
  at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:75)
  at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:641)
  ... 49 elided
```

I've tried various combinations of kinit, --proxy-user and --principal, but none of them worked. The goal would be using either kinit or --principal. Could you provide some guidance maybe? 

Thank you very much!

**Comment by yaooqinn** [comment]
you may check hive.security.authenticator.manager in hive-site.xml

**Comment by spacenorden** [comment]
Thank you Kent. That value is set to
`org.apache.hadoop.hive.ql.security.ProxyUserAuthenticator`
What should it rather be?
`org.apache.hadoop.hive.ql.security.SessionStateUserAuthenticator`
?

**Comment by spacenorden** [comment]
Thanks Kent, that was the right hint! I had it set to
`org.apache.hadoop.hive.ql.security.SessionStateUserAuthenticator`
as instructed and included in the example config in /conf/hive-site.xml, but before it was
`org.apache.hadoop.hive.ql.security.ProxyUserAuthenticator`
in our cluster. After setting it back to that, it worked!
