### ISSUE TITLE
java.lang.LinkageError  when execute spark sql

### ISSUE THREAD

**Issue by west-xrz** [yaooqinn/spark-authorizer#5]
Hello,
I am using hive 2.1.1 and spark 2.1.2
when I execute the spark sql command, it show the following error:

`scala> sql("show tables").show`
`18/09/26 09:54:02 WARN session.SessionState: METASTORE_FILTER_HOOK will be ignored, since hive.security.authorization.manager is set to instance of HiveAuthorizerFactory.
java.lang.LinkageError: loader constraint violation: loader (instance of sun/misc/Launcher$AppClassLoader) previously initiated loading for a different type with name "org/apache/hadoop/hive/ql/security/authorization/plugin/HiveOperationType"
  at java.lang.ClassLoader.defineClass1(Native Method)
  at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
  at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
  at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)
  at java.net.URLClassLoader.access$100(URLClassLoader.java:64)
  at java.net.URLClassLoader$1.run(URLClassLoader.java:354)
  at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
  at java.security.AccessController.doPrivileged(Native Method)
  at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
  at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:312)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
  at org.apache.spark.sql.catalyst.optimizer.Authorizer$.toHiveOperationType(Authorizer.scala:150)
  at org.apache.spark.sql.catalyst.optimizer.Authorizer$.apply(Authorizer.scala:54)
  at org.apache.spark.sql.catalyst.optimizer.Authorizer$.apply(Authorizer.scala:42)
  at org.apache.spark.sql.catalyst.rules.RuleExecutor$$anonfun$execute$1$$anonfun$apply$1.apply(RuleExecutor.scala:85)
  at org.apache.spark.sql.catalyst.rules.RuleExecutor$$anonfun$execute$1$$anonfun$apply$1.apply(RuleExecutor.scala:82)
  at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
  at scala.collection.immutable.List.foldLeft(List.scala:84)
  at org.apache.spark.sql.catalyst.rules.RuleExecutor$$anonfun$execute$1.apply(RuleExecutor.scala:82)
  at org.apache.spark.sql.catalyst.rules.RuleExecutor$$anonfun$execute$1.apply(RuleExecutor.scala:74)
  at scala.collection.immutable.List.foreach(List.scala:381)
  at org.apache.spark.sql.catalyst.rules.RuleExecutor.execute(RuleExecutor.scala:74)
  at org.apache.spark.sql.execution.QueryExecution.optimizedPlan$lzycompute(QueryExecution.scala:78)
  at org.apache.spark.sql.execution.QueryExecution.optimizedPlan(QueryExecution.scala:78)
  at org.apache.spark.sql.execution.QueryExecution.sparkPlan$lzycompute(QueryExecution.scala:84)
  at org.apache.spark.sql.execution.QueryExecution.sparkPlan(QueryExecution.scala:80)
  at org.apache.spark.sql.execution.QueryExecution.executedPlan$lzycompute(QueryExecution.scala:89)
  at org.apache.spark.sql.execution.QueryExecution.executedPlan(QueryExecution.scala:89)
  at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:92)
  at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:92)
  at org.apache.spark.sql.Dataset.<init>(Dataset.scala:185)
  at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:64)
  at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:600)`

I just follow the instructions in readme , could you have any idea about this ?
or something I missed ?

Thank you~
Leon

**Comment by yaooqinn** [comment]
hive 2.1.1 as metastore server or client，we only support builtin hive jars（1.2.1.spark2）as client jars

**Comment by west-xrz** [comment]
thank for your response~
now I change to use ranger 0.5.3 and hive 1.2.2 and spark 2.1 , but still has following exception:
`scala> sql("show tables").show
java.lang.LinkageError: loader constraint violation: loader (instance of sun/misc/Launcher$AppClassLoader) previously initiated loading for a different type with name "org/apache/hadoop/hive/ql/security/authorization/plugin/HiveOperationType"
  at java.lang.ClassLoader.defineClass1(Native Method)
  at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
  at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
  at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)
  at java.net.URLClassLoader.access$100(URLClassLoader.java:64)
  at java.net.URLClassLoader$1.run(URLClassLoader.java:354)
  at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
  at java.security.AccessController.doPrivileged(Native Method)
  at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
  at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:312)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
  at org.apache.spark.sql.catalyst.optimizer.Authorizer$.getOperationType(Authorizer.scala:185)
  at org.apache.spark.sql.catalyst.optimizer.Authorizer$.apply(Authorizer.scala:59)
  at org.apache.spark.sql.catalyst.optimizer.Authorizer$.apply(Authorizer.scala:47)
  at org.apache.spark.sql.catalyst.rules.RuleExecutor$$anonfun$execute$1$$anonfun$apply$1.apply(RuleExecutor.scala:85)
  at org.apache.spark.sql.catalyst.rules.RuleExecutor$$anonfun$execute$1$$anonfun$apply$1.apply(RuleExecutor.scala:82)
  at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
  at scala.collection.immutable.List.foldLeft(List.scala:84)
  at org.apache.spark.sql.catalyst.rules.RuleExecutor$$anonfun$execute$1.apply(RuleExecutor.scala:82)
  at org.apache.spark.sql.catalyst.rules.RuleExecutor$$anonfun$execute$1.apply(RuleExecutor.scala:74)
  at scala.collection.immutable.List.foreach(List.scala:381)
  at org.apache.spark.sql.catalyst.rules.RuleExecutor.execute(RuleExecutor.scala:74)
  at org.apache.spark.sql.execution.QueryExecution.optimizedPlan$lzycompute(QueryExecution.scala:78)
  at org.apache.spark.sql.execution.QueryExecution.optimizedPlan(QueryExecution.scala:78)
  at org.apache.spark.sql.execution.QueryExecution.sparkPlan$lzycompute(QueryExecution.scala:84)
  at org.apache.spark.sql.execution.QueryExecution.sparkPlan(QueryExecution.scala:80)
  at org.apache.spark.sql.execution.QueryExecution.executedPlan$lzycompute(QueryExecution.scala:89)
  at org.apache.spark.sql.execution.QueryExecution.executedPlan(QueryExecution.scala:89)
  at org.apache.spark.sql.Dataset.withTypedCallback(Dataset.scala:2814)
  at org.apache.spark.sql.Dataset.head(Dataset.scala:2127)
  at org.apache.spark.sql.Dataset.take(Dataset.scala:2342)
  at org.apache.spark.sql.Dataset.showString(Dataset.scala:248)
  at org.apache.spark.sql.Dataset.show(Dataset.scala:640)
  at org.apache.spark.sql.Dataset.show(Dataset.scala:617)
  ... 53 elided
`

is there something i missed ? thank you.

Regards,
Leon

**Comment by yaooqinn** [comment]
please refer to https://yaooqinn.github.io/spark-authorizer/docs/install_plugin.html

**Comment by west-xrz** [comment]
Hello,
The issue solved , it works well now (spark2.1 , hive 2.1 metastore, ranger0.5.3), 
Thank you very much~

May I ask do you have the plan that spark-authorizer can support using higher version of ranger ?

Regards,
Leon

**Comment by yaooqinn** [comment]
@west-xrz Glad I could help. 
And please pay attention to this jira ticket https://issues.apache.org/jira/browse/RANGER-2128, which may contains a final answer to your question.

**Comment by west-xrz** [comment]
Hello YaoOqinn, 
It's good to hear from you about the integration with Ranger, I am also interesting on it , is there experimental code that I can have a try ?
